# GitLab CI configuration.

.golang_template: &golang
  script:
    - make test

golang_1.15:
  <<: *golang
  # This image doesn't have Python 3 by default.
  before_script:
    - apt update
    - apt install -y python3
  image: golang:1.15    # Version in Debian stable.

golang_latest:
  <<: *golang
  image: golang:latest
