# Configuration for https://travis-ci.org/

dist: bionic

language: go
go_import_path: blitiri.com.ar/go/kxd

go:
    - 1.11  # Debian stable.
    - stable
    - master

addons:
    apt:
        packages:
            - python3

# Nothing to do for install, the tests will build the binaries anyway.
install: true

script:
    - make test

